### ISSUE TITLE
A very ambitious revamp!

### ISSUE THREAD

**Issue by JamenMarz** [JamenMarz/pheo#2]
I recently wanted to get involved in [Electron](http://electron.atom.io/) and it's community, so I though a good place to stat learning would be to revamp vint once I learn some basics about Electron...

This is a huge task, but as the title suggests, I'm ambitious.

**Comment by austinkregel** [comment]
Best of luck :D

**Comment by JamenMarz** [comment]
Progress is good, planning on doing a pre-release of the current functionality, which is basically just a chat field.
